listen = 80
listen_ssl = 443
server_name = "your.site"
# logging_enabled = true
# ssl_certificate = "/etc/letsencrypt/live/your.site/fullchain.pem"
# ssl_certificate_key = "/etc/letsencrypt/live/your.site/privkey.pem"
# letsencrypt = true
# redirect_http = true

[[custom_keywords]]
phrase = "nginx"
dest = "wikipedia"

[[custom_keywords]]
phrase = "New York"
dest = "wikipedia"

[[custom_keywords]]
phrase = "openai"
dest = "wikipedia"

[[custom_keywords]]
phrase = "cat pictures"
dest = "google_images"
