---
name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NGINX_VERSION: latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Go Tests
        run: go test ./...
      - name: Cache nginx image
        id: cache-nginx
        uses: actions/cache@v3
        with:
          path: ~/.cache/nginx.tar
          key: ${{ runner.os }}-nginx-${{ env.NGINX_VERSION }}
      - name: Load nginx image from cache
        if: steps.cache-nginx.outputs.cache-hit == 'true'
        run: docker load -i ~/.cache/nginx.tar
      - name: Pull nginx image
        if: steps.cache-nginx.outputs.cache-hit != 'true'
        run: |
          docker pull "nginx:$NGINX_VERSION"
          mkdir -p ~/.cache
          docker save "nginx:$NGINX_VERSION" -o ~/.cache/nginx.tar
      - name: Validate generated nginx config
        run: |
          go run ./cmd/sea/main.go > nginx.conf
          docker run --rm \
            -v "$PWD/nginx.conf:/etc/nginx/conf.d/default.conf:ro" \
            "nginx:$NGINX_VERSION" \
            nginx -t
